name: Build Docker Image

on:
  release:
    types: [published]
  push:
    branches:
      - develop


jobs:

  build-and-transfer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/kealy-apps/fastapi-template:latest
          build-args: |
            GIT_TAG=0.0.0

      - name: Build and push tagged Docker image from Release
        if: github.event_name == 'release'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/kealy-apps/fastapi-template:latest,ghcr.io/kealy-apps/fastapi-template:${{ github.event.release.tag_name }}
          build-args: |
            GIT_TAG={{ github.event.release.tag_name }}
